# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-gatkcohortcall-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - bwa=0.7.17
  - fastqc=0.11.8
  - gatk4=4.1.2.0
  - htslib=1.9
  - samtools=1.9
  - vcftools=0.1.16

